# Generated by Django 5.0.14 on 2025-10-23 16:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id_autore', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_autore', models.CharField(max_length=20)),
                ('cognome_autore', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=30)),
                ('descrizione', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Postazione',
            fields=[
                ('id_postazione', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('posizione', models.CharField(max_length=2)),
                ('numerazione', models.PositiveIntegerField()),
                ('capacita', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postazione_categoria', to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=30)),
                ('data_uscita', models.DateField()),
                ('editore', models.CharField(max_length=20)),
                ('formato', models.CharField(max_length=50)),
                ('lingua', models.CharField(max_length=20)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_autore', to='api.autore')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_utente', to=settings.AUTH_USER_MODEL)),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_postazione', to='api.postazione')),
            ],
        ),
        migrations.CreateModel(
            name='TesseraBiblioteca',
            fields=[
                ('id_tessera', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_tesserato', models.CharField(max_length=20)),
                ('cognome_tesserato', models.CharField(max_length=50)),
                ('data_nascita', models.DateField()),
                ('codice_fiscale', models.CharField(max_length=11)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('indirizzo', models.CharField(max_length=120)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesserabiblioteca_utente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestito',
            fields=[
                ('id_prestito', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('isRestituito', models.BooleanField(default=False)),
                ('isPrestato', models.BooleanField(default=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestito_libro', to='api.libro')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestito_utente', to=settings.AUTH_USER_MODEL)),
                ('tesserato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestito_tesserato', to='api.tesserabiblioteca')),
            ],
        ),
    ]
